require('dotenv').config();
const mongoose = require('mongoose');
const State = require('../models/State');
const City = require('../models/City');
const connectDB = require('../config/database');

// Connect to database
connectDB();

// All Indian States and Union Territories Data
const allStatesData = [
  {
    name: "Andhra Pradesh",
    slug: "andhra-pradesh",
    description: "Andhra Pradesh is known for its rich cultural heritage, beautiful beaches, ancient temples, and delicious cuisine. It's a perfect blend of history, spirituality, and natural beauty. Famous for Tirupati Temple, beautiful beaches of Visakhapatnam, and the rich agricultural lands.",
    shortDescription: "Temple State - Heritage, Beaches & Culture",
    heroImage: "https://images.unsplash.com/photo-1582510003544-4d00b7f74220?w=1920&q=90",
    capital: "Amaravati",
    area: "160,205 km²",
    population: "49 million",
    languages: ["Telugu", "Hindi", "English"],
    bestTimeToVisit: "October to March",
    featured: true,
    isActive: true,
    order: 2,
    region: "South",
    metaTitle: "Andhra Pradesh Tourism - Temple State Travel Guide",
    metaDescription: "Explore Andhra Pradesh - Tirupati Temple, beaches, heritage sites. Best time to visit, attractions, and tour packages.",
    metaKeywords: "Andhra Pradesh, Tirupati, Visakhapatnam, beaches, temples, tourism"
  },
  {
    name: "Arunachal Pradesh",
    slug: "arunachal-pradesh",
    description: "Arunachal Pradesh, the Land of the Dawn-Lit Mountains, is India's northeastern paradise. Known for its pristine natural beauty, diverse tribal cultures, Buddhist monasteries, and untouched wilderness. A haven for nature lovers and adventure enthusiasts.",
    shortDescription: "Land of Dawn - Nature, Adventure & Culture",
    heroImage: "https://images.unsplash.com/photo-1626621341517-bbf3d9990a23?w=1920&q=90",
    capital: "Itanagar",
    area: "83,743 km²",
    population: "1.4 million",
    languages: ["English", "Hindi", "Various tribal languages"],
    bestTimeToVisit: "October to April",
    featured: false,
    isActive: true,
    order: 3,
    region: "Northeast",
    metaTitle: "Arunachal Pradesh Tourism - Northeast Paradise Guide",
    metaDescription: "Visit Arunachal Pradesh - pristine nature, Buddhist monasteries, tribal culture. Adventure and nature tourism.",
    metaKeywords: "Arunachal Pradesh, Northeast India, Tawang, Buddhist monasteries, nature tourism"
  },
  {
    name: "Assam",
    slug: "assam",
    description: "Assam is famous for its tea gardens, one-horned rhinoceros, ancient temples, and rich cultural heritage. Home to Kaziranga National Park, Majuli Island, and the mighty Brahmaputra River. Known for Assamese silk, traditional dance forms, and warm hospitality.",
    shortDescription: "Tea State - Wildlife, Culture & Nature",
    heroImage: "https://images.unsplash.com/photo-1545569341-9eb8b30979d9?w=1920&q=90",
    capital: "Dispur",
    area: "78,438 km²",
    population: "31 million",
    languages: ["Assamese", "Bodo", "Bengali", "English"],
    bestTimeToVisit: "October to April",
    featured: true,
    isActive: true,
    order: 4,
    region: "Northeast",
    metaTitle: "Assam Tourism - Tea Gardens & Kaziranga Guide",
    metaDescription: "Explore Assam - Kaziranga National Park, tea gardens, Majuli Island, Kamakhya Temple. Wildlife and cultural tourism.",
    metaKeywords: "Assam, Kaziranga, one-horned rhino, tea gardens, Majuli, Brahmaputra"
  },
  {
    name: "Bihar",
    slug: "bihar",
    description: "Bihar is one of India's oldest states with rich historical and cultural heritage. Birthplace of Buddhism and Jainism, home to ancient universities like Nalanda, and important pilgrimage sites. Known for its educational centers, Buddhist stupas, and traditional arts.",
    shortDescription: "Land of Enlightenment - Heritage, Spiritual & Culture",
    heroImage: "https://images.unsplash.com/photo-1564501049412-61c2a3083791?w=1920&q=90",
    capital: "Patna",
    area: "94,163 km²",
    population: "104 million",
    languages: ["Hindi", "Maithili", "Bhojpuri", "English"],
    bestTimeToVisit: "October to March",
    featured: false,
    isActive: true,
    order: 5,
    region: "East",
    metaTitle: "Bihar Tourism - Land of Enlightenment Guide",
    metaDescription: "Visit Bihar - Nalanda University, Buddhist sites, Bodh Gaya, Patna. Spiritual and heritage tourism.",
    metaKeywords: "Bihar, Nalanda, Bodh Gaya, Buddhist sites, Patna, heritage tourism"
  },
  {
    name: "Chhattisgarh",
    slug: "chhattisgarh",
    description: "Chhattisgarh is known for its rich tribal culture, ancient caves, waterfalls, and dense forests. Home to Chitrakoot Falls, Bastar region with unique tribal traditions, and significant mineral resources. A destination for nature lovers and culture enthusiasts.",
    shortDescription: "Rice Bowl - Tribal Culture, Nature & Heritage",
    heroImage: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=1920&q=90",
    capital: "Raipur",
    area: "135,191 km²",
    population: "29 million",
    languages: ["Hindi", "Chhattisgarhi", "English"],
    bestTimeToVisit: "October to March",
    featured: false,
    isActive: true,
    order: 6,
    region: "Central",
    metaTitle: "Chhattisgarh Tourism - Tribal Culture & Nature Guide",
    metaDescription: "Explore Chhattisgarh - tribal culture, waterfalls, caves, Bastar. Nature and cultural tourism.",
    metaKeywords: "Chhattisgarh, Bastar, tribal culture, Chitrakoot Falls, Raipur, nature tourism"
  },
  {
    name: "Goa",
    slug: "goa",
    description: "Goa is India's party capital and beach paradise. Known for pristine beaches, Portuguese architecture, vibrant nightlife, and delicious seafood. A perfect blend of relaxation, adventure, and cultural exploration. Famous for its laid-back vibe and beautiful churches.",
    shortDescription: "Beach Paradise - Beaches, Nightlife & Culture",
    heroImage: "https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?w=1920&q=90",
    capital: "Panaji",
    area: "3,702 km²",
    population: "1.5 million",
    languages: ["Konkani", "English", "Hindi", "Portuguese"],
    bestTimeToVisit: "October to March (November to February best)",
    featured: true,
    isActive: true,
    order: 7,
    region: "West",
    metaTitle: "Goa Tourism - Beach Paradise Complete Guide",
    metaDescription: "Experience Goa - beautiful beaches, nightlife, Portuguese heritage, seafood. Best beach destination in India.",
    metaKeywords: "Goa, beaches, nightlife, Portuguese architecture, Panaji, beach tourism"
  },
  {
    name: "Gujarat",
    slug: "gujarat",
    description: "Gujarat is known for its rich history, vibrant culture, business hubs, and diverse landscapes. Home to the Statue of Unity, Rann of Kutch, Asiatic lions in Gir, and important pilgrimage sites. Famous for Gujarati cuisine, festivals, and industrial development.",
    shortDescription: "Business Hub - Heritage, Nature & Culture",
    heroImage: "https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=1920&q=90",
    capital: "Gandhinagar",
    area: "196,024 km²",
    population: "60 million",
    languages: ["Gujarati", "Hindi", "English"],
    bestTimeToVisit: "October to March",
    featured: true,
    isActive: true,
    order: 8,
    region: "West",
    metaTitle: "Gujarat Tourism - Business Hub Travel Guide",
    metaDescription: "Visit Gujarat - Statue of Unity, Rann of Kutch, Gir National Park, heritage sites. Business and tourism hub.",
    metaKeywords: "Gujarat, Statue of Unity, Rann of Kutch, Gir National Park, Ahmedabad, heritage"
  },
  {
    name: "Haryana",
    slug: "haryana",
    description: "Haryana is known for its agricultural prosperity, industrial growth, and rich cultural heritage. Home to Kurukshetra (battlefield of Mahabharata), beautiful temples, and modern cities. Famous for dairy farming, sports achievements, and traditional crafts.",
    shortDescription: "Breadbasket - Heritage, Culture & Industry",
    heroImage: "https://images.unsplash.com/photo-1539650116574-75c0c6d73ab6?w=1920&q=90",
    capital: "Chandigarh",
    area: "44,212 km²",
    population: "25 million",
    languages: ["Hindi", "Haryanvi", "English"],
    bestTimeToVisit: "October to March",
    featured: false,
    isActive: true,
    order: 9,
    region: "North",
    metaTitle: "Haryana Tourism - Heritage & Culture Guide",
    metaDescription: "Explore Haryana - Kurukshetra, heritage sites, industrial hubs. Cultural and heritage tourism.",
    metaKeywords: "Haryana, Kurukshetra, Chandigarh, heritage, culture, tourism"
  },
  {
    name: "Himachal Pradesh",
    slug: "himachal-pradesh",
    description: "Himachal Pradesh is India's adventure capital and hill station paradise. Known for snow-capped mountains, beautiful valleys, adventure sports, and hill stations like Shimla and Manali. Perfect for trekking, skiing, and mountain lovers.",
    shortDescription: "Mountain Paradise - Adventure, Hill Stations & Nature",
    heroImage: "https://images.unsplash.com/photo-1626621341517-bbf3d9990a23?w=1920&q=90",
    capital: "Shimla",
    area: "55,673 km²",
    population: "6.8 million",
    languages: ["Hindi", "Pahari", "English"],
    bestTimeToVisit: "April to June and October to February (snow season)",
    featured: true,
    isActive: true,
    order: 10,
    region: "North",
    metaTitle: "Himachal Pradesh Tourism - Mountain Paradise Guide",
    metaDescription: "Experience Himachal Pradesh - Shimla, Manali, adventure sports, trekking, snow tourism. Best hill stations in India.",
    metaKeywords: "Himachal Pradesh, Shimla, Manali, adventure sports, trekking, hill stations, snow"
  },
  {
    name: "Jharkhand",
    slug: "jharkhand",
    description: "Jharkhand is known for its rich mineral resources, tribal culture, waterfalls, and ancient temples. Home to Betla National Park, Hundru Falls, and significant industrial centers. A destination for nature lovers and those interested in tribal heritage.",
    shortDescription: "Mining State - Nature, Tribal Culture & Industry",
    heroImage: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=1920&q=90",
    capital: "Ranchi",
    area: "79,714 km²",
    population: "33 million",
    languages: ["Hindi", "Santali", "English"],
    bestTimeToVisit: "October to March",
    featured: false,
    isActive: true,
    order: 11,
    region: "East",
    metaTitle: "Jharkhand Tourism - Nature & Culture Guide",
    metaDescription: "Visit Jharkhand - waterfalls, tribal culture, Betla National Park, industrial hubs. Nature and cultural tourism.",
    metaKeywords: "Jharkhand, Ranchi, waterfalls, tribal culture, Betla National Park"
  },
  {
    name: "Karnataka",
    slug: "karnataka",
    description: "Karnataka offers a perfect blend of heritage, beaches, hill stations, and modern technology hubs. Known for Mysore Palace, beautiful beaches of Gokarna, tech capital Bangalore, ancient temples of Hampi, and coffee plantations of Coorg.",
    shortDescription: "Silicon Valley - Heritage, Beaches & Technology",
    heroImage: "https://images.unsplash.com/photo-1587135941948-670b381f08ce?w=1920&q=90",
    capital: "Bangalore",
    area: "191,791 km²",
    population: "61 million",
    languages: ["Kannada", "English", "Hindi"],
    bestTimeToVisit: "October to March",
    featured: true,
    isActive: true,
    order: 12,
    region: "South",
    metaTitle: "Karnataka Tourism - Silicon Valley Travel Guide",
    metaDescription: "Explore Karnataka - Bangalore, Mysore, Hampi, Coorg, Gokarna beaches. Heritage, tech, and nature tourism.",
    metaKeywords: "Karnataka, Bangalore, Mysore, Hampi, Coorg, Gokarna, tech hub, heritage"
  },
  {
    name: "Kerala",
    slug: "kerala",
    description: "Kerala, God's Own Country, is famous for its backwaters, hill stations, Ayurveda, and serene beauty. Known for houseboats in Alleppey, tea plantations in Munnar, beautiful beaches, and rich cultural heritage. A perfect destination for relaxation and wellness.",
    shortDescription: "God's Own Country - Backwaters, Hill Stations & Ayurveda",
    heroImage: "https://images.unsplash.com/photo-1602216056096-3b40cc0c9944?w=1920&q=90",
    capital: "Thiruvananthapuram",
    area: "38,863 km²",
    population: "34 million",
    languages: ["Malayalam", "English", "Hindi"],
    bestTimeToVisit: "October to March",
    featured: true,
    isActive: true,
    order: 13,
    region: "South",
    metaTitle: "Kerala Tourism - God's Own Country Complete Guide",
    metaDescription: "Experience Kerala - backwaters, hill stations, Ayurveda, beaches, houseboats. Best wellness and nature destination.",
    metaKeywords: "Kerala, backwaters, Munnar, Alleppey, Ayurveda, houseboats, God's Own Country"
  },
  {
    name: "Madhya Pradesh",
    slug: "madhya-pradesh",
    description: "Madhya Pradesh, the Heart of India, is known for its rich heritage, wildlife sanctuaries, and architectural marvels. Home to Khajuraho temples, Bandhavgarh and Kanha tiger reserves, ancient forts, and historical cities. A perfect blend of history and nature.",
    shortDescription: "Heart of India - Heritage, Wildlife & History",
    heroImage: "https://images.unsplash.com/photo-1582407947304-fd86f028f716?w=1920&q=90",
    capital: "Bhopal",
    area: "308,245 km²",
    population: "73 million",
    languages: ["Hindi", "English"],
    bestTimeToVisit: "October to March",
    featured: true,
    isActive: true,
    order: 14,
    region: "Central",
    metaTitle: "Madhya Pradesh Tourism - Heart of India Guide",
    metaDescription: "Visit Madhya Pradesh - Khajuraho, tiger reserves, ancient forts, Bhopal. Heritage and wildlife tourism.",
    metaKeywords: "Madhya Pradesh, Khajuraho, Bandhavgarh, Kanha, tiger reserves, heritage, Bhopal"
  },
  {
    name: "Maharashtra",
    slug: "maharashtra",
    description: "Maharashtra is India's financial and entertainment capital. Known for Mumbai (Bollywood), ancient caves of Ajanta and Ellora, hill stations like Lonavala, beaches of Konkan coast, and delicious cuisine. A perfect mix of modernity and heritage.",
    shortDescription: "Financial Capital - Heritage, Beaches & Entertainment",
    heroImage: "https://images.unsplash.com/photo-1595658658481-d53d3f999875?w=1920&q=90",
    capital: "Mumbai",
    area: "307,713 km²",
    population: "112 million",
    languages: ["Marathi", "Hindi", "English"],
    bestTimeToVisit: "October to March",
    featured: true,
    isActive: true,
    order: 15,
    region: "West",
    metaTitle: "Maharashtra Tourism - Financial Capital Guide",
    metaDescription: "Explore Maharashtra - Mumbai, Ajanta Ellora caves, hill stations, beaches. Business, heritage, and entertainment hub.",
    metaKeywords: "Maharashtra, Mumbai, Ajanta Ellora, Lonavala, beaches, Bollywood, financial capital"
  },
  {
    name: "Manipur",
    slug: "manipur",
    description: "Manipur, the Jewel of India, is known for its natural beauty, unique culture, and traditional dance forms. Famous for Loktak Lake (floating phumdis), Sangai deer, beautiful valleys, and rich cultural heritage. A hidden gem of Northeast India.",
    shortDescription: "Jewel of India - Nature, Culture & Lakes",
    heroImage: "https://images.unsplash.com/photo-1545569341-9eb8b30979d9?w=1920&q=90",
    capital: "Imphal",
    area: "22,327 km²",
    population: "2.7 million",
    languages: ["Manipuri", "English", "Hindi"],
    bestTimeToVisit: "October to March",
    featured: false,
    isActive: true,
    order: 16,
    region: "Northeast",
    metaTitle: "Manipur Tourism - Jewel of India Guide",
    metaDescription: "Experience Manipur - Loktak Lake, Sangai, traditional culture, natural beauty. Northeast paradise.",
    metaKeywords: "Manipur, Loktak Lake, Imphal, Sangai, traditional dance, Northeast India"
  },
  {
    name: "Meghalaya",
    slug: "meghalaya",
    description: "Meghalaya, the Abode of Clouds, is famous for its living root bridges, waterfalls, caves, and beautiful hill stations. Known for Cherrapunji (wettest place on Earth), Mawlynnong (Asia's cleanest village), and unique Khasi culture. A nature lover's paradise.",
    shortDescription: "Abode of Clouds - Nature, Culture & Adventure",
    heroImage: "https://images.unsplash.com/photo-1626621341517-bbf3d9990a23?w=1920&q=90",
    capital: "Shillong",
    area: "22,429 km²",
    population: "3 million",
    languages: ["English", "Khasi", "Garo"],
    bestTimeToVisit: "April to June and September to November",
    featured: false,
    isActive: true,
    order: 17,
    region: "Northeast",
    metaTitle: "Meghalaya Tourism - Abode of Clouds Guide",
    metaDescription: "Visit Meghalaya - Cherrapunji, living root bridges, waterfalls, Shillong. Nature and adventure tourism.",
    metaKeywords: "Meghalaya, Cherrapunji, Shillong, living root bridges, Mawlynnong, waterfalls"
  },
  {
    name: "Mizoram",
    slug: "mizoram",
    description: "Mizoram is known for its scenic beauty, rich biodiversity, and unique Mizo culture. Famous for its rolling hills, traditional bamboo dances, beautiful landscapes, and warm hospitality. One of the most peaceful states in India with pristine natural beauty.",
    shortDescription: "Land of Highlanders - Nature, Culture & Peace",
    heroImage: "https://images.unsplash.com/photo-1545569341-9eb8b30979d9?w=1920&q=90",
    capital: "Aizawl",
    area: "21,081 km²",
    population: "1.1 million",
    languages: ["Mizo", "English", "Hindi"],
    bestTimeToVisit: "October to March",
    featured: false,
    isActive: true,
    order: 18,
    region: "Northeast",
    metaTitle: "Mizoram Tourism - Land of Highlanders Guide",
    metaDescription: "Explore Mizoram - Aizawl, natural beauty, Mizo culture, biodiversity. Peaceful Northeast destination.",
    metaKeywords: "Mizoram, Aizawl, Mizo culture, natural beauty, Northeast India"
  },
  {
    name: "Nagaland",
    slug: "nagaland",
    description: "Nagaland is famous for its vibrant tribal culture, Hornbill Festival, beautiful landscapes, and rich traditions. Known for its 16 major tribes, unique customs, beautiful hills, and warm Naga hospitality. A destination for culture and adventure enthusiasts.",
    shortDescription: "Land of Festivals - Culture, Nature & Adventure",
    heroImage: "https://images.unsplash.com/photo-1626621341517-bbf3d9990a23?w=1920&q=90",
    capital: "Kohima",
    area: "16,579 km²",
    population: "2 million",
    languages: ["English", "Nagamese", "Various tribal languages"],
    bestTimeToVisit: "October to May",
    featured: false,
    isActive: true,
    order: 19,
    region: "Northeast",
    metaTitle: "Nagaland Tourism - Land of Festivals Guide",
    metaDescription: "Experience Nagaland - Hornbill Festival, tribal culture, Kohima, natural beauty. Cultural and adventure tourism.",
    metaKeywords: "Nagaland, Hornbill Festival, Kohima, tribal culture, Naga tribes, Northeast India"
  },
  {
    name: "Odisha",
    slug: "odisha",
    description: "Odisha is known for its ancient temples, beautiful beaches, rich cultural heritage, and tribal art. Famous for Konark Sun Temple, Jagannath Temple in Puri, beautiful beaches of Puri and Gopalpur, and traditional Odissi dance. A perfect blend of spirituality and nature.",
    shortDescription: "Temple State - Heritage, Beaches & Culture",
    heroImage: "https://images.unsplash.com/photo-1582407947304-fd86f028f716?w=1920&q=90",
    capital: "Bhubaneswar",
    area: "155,707 km²",
    population: "42 million",
    languages: ["Odia", "English", "Hindi"],
    bestTimeToVisit: "October to March",
    featured: true,
    isActive: true,
    order: 20,
    region: "East",
    metaTitle: "Odisha Tourism - Temple State Guide",
    metaDescription: "Visit Odisha - Konark Temple, Jagannath Temple, Puri beaches, Bhubaneswar. Heritage and beach tourism.",
    metaKeywords: "Odisha, Konark, Puri, Jagannath Temple, Bhubaneswar, beaches, heritage"
  },
  {
    name: "Punjab",
    slug: "punjab",
    description: "Punjab, the Land of Five Rivers, is known for its rich culture, delicious cuisine, golden temples, and agricultural prosperity. Famous for Golden Temple in Amritsar, vibrant festivals, warm hospitality, and hearty Punjabi food. A destination for spirituality and culture.",
    shortDescription: "Land of Five Rivers - Culture, Heritage & Cuisine",
    heroImage: "https://images.unsplash.com/photo-1539650116574-75c0c6d73ab6?w=1920&q=90",
    capital: "Chandigarh",
    area: "50,362 km²",
    population: "27 million",
    languages: ["Punjabi", "Hindi", "English"],
    bestTimeToVisit: "October to March",
    featured: true,
    isActive: true,
    order: 21,
    region: "North",
    metaTitle: "Punjab Tourism - Land of Five Rivers Guide",
    metaDescription: "Explore Punjab - Golden Temple, Amritsar, culture, cuisine. Spiritual and cultural destination.",
    metaKeywords: "Punjab, Golden Temple, Amritsar, culture, cuisine, spiritual tourism"
  },
  {
    name: "Sikkim",
    slug: "sikkim",
    description: "Sikkim is a small but stunning Himalayan state known for its natural beauty, Buddhist monasteries, and adventure tourism. Famous for Mount Kanchenjunga views, beautiful valleys, serene monasteries, and adventure activities. A perfect destination for nature and spirituality.",
    shortDescription: "Himalayan Paradise - Nature, Adventure & Spirituality",
    heroImage: "https://images.unsplash.com/photo-1626621341517-bbf3d9990a23?w=1920&q=90",
    capital: "Gangtok",
    area: "7,096 km²",
    population: "610,000",
    languages: ["Nepali", "English", "Hindi", "Sikkimese"],
    bestTimeToVisit: "March to May and October to December",
    featured: true,
    isActive: true,
    order: 22,
    region: "Northeast",
    metaTitle: "Sikkim Tourism - Himalayan Paradise Guide",
    metaDescription: "Experience Sikkim - Gangtok, Kanchenjunga, monasteries, adventure sports. Himalayan beauty and spirituality.",
    metaKeywords: "Sikkim, Gangtok, Kanchenjunga, monasteries, adventure, Himalayan paradise"
  },
  {
    name: "Tamil Nadu",
    slug: "tamil-nadu",
    description: "Tamil Nadu is known for its magnificent temples, rich culture, beautiful hill stations, and classical arts. Famous for Meenakshi Temple, Ooty hill station, Marina Beach, classical dance forms, and delicious cuisine. A perfect blend of spirituality, culture, and nature.",
    shortDescription: "Temple State - Heritage, Hill Stations & Culture",
    heroImage: "https://images.unsplash.com/photo-1582407947304-fd86f028f716?w=1920&q=90",
    capital: "Chennai",
    area: "130,058 km²",
    population: "72 million",
    languages: ["Tamil", "English", "Hindi"],
    bestTimeToVisit: "October to March",
    featured: true,
    isActive: true,
    order: 23,
    region: "South",
    metaTitle: "Tamil Nadu Tourism - Temple State Guide",
    metaDescription: "Visit Tamil Nadu - Chennai, Meenakshi Temple, Ooty, hill stations, beaches. Heritage and nature tourism.",
    metaKeywords: "Tamil Nadu, Chennai, Meenakshi Temple, Ooty, hill stations, culture, heritage"
  },
  {
    name: "Telangana",
    slug: "telangana",
    description: "Telangana is a modern state with rich history and culture. Known for Hyderabad (City of Pearls), iconic Charminar, delicious Hyderabadi biryani, IT industry, and ancient forts. A perfect blend of tradition and modernity.",
    shortDescription: "City of Pearls - Heritage, Technology & Cuisine",
    heroImage: "https://images.unsplash.com/photo-1582510003544-4d00b7f74220?w=1920&q=90",
    capital: "Hyderabad",
    area: "112,077 km²",
    population: "35 million",
    languages: ["Telugu", "Urdu", "Hindi", "English"],
    bestTimeToVisit: "October to March",
    featured: true,
    isActive: true,
    order: 24,
    region: "South",
    metaTitle: "Telangana Tourism - City of Pearls Guide",
    metaDescription: "Explore Telangana - Hyderabad, Charminar, biryani, IT hub, ancient forts. Heritage and modern tourism.",
    metaKeywords: "Telangana, Hyderabad, Charminar, biryani, IT hub, heritage, technology"
  },
  {
    name: "Tripura",
    slug: "tripura",
    description: "Tripura is a small northeastern state known for its royal palaces, beautiful landscapes, and rich cultural heritage. Famous for Ujjayanta Palace, beautiful lakes, ancient temples, and unique tribal culture. A hidden gem of Northeast India.",
    shortDescription: "Land of Royalty - Heritage, Culture & Nature",
    heroImage: "https://images.unsplash.com/photo-1545569341-9eb8b30979d9?w=1920&q=90",
    capital: "Agartala",
    area: "10,491 km²",
    population: "3.7 million",
    languages: ["Bengali", "Kokborok", "English", "Hindi"],
    bestTimeToVisit: "October to March",
    featured: false,
    isActive: true,
    order: 25,
    region: "Northeast",
    metaTitle: "Tripura Tourism - Land of Royalty Guide",
    metaDescription: "Visit Tripura - Agartala, Ujjayanta Palace, lakes, temples. Heritage and cultural tourism.",
    metaKeywords: "Tripura, Agartala, Ujjayanta Palace, Northeast India, culture, heritage"
  },
  {
    name: "Uttar Pradesh",
    slug: "uttar-pradesh",
    description: "Uttar Pradesh is India's most populous state with rich history, culture, and spirituality. Famous for Taj Mahal in Agra, spiritual cities Varanasi and Ayodhya, Lucknow's culture, and numerous historical monuments. A perfect destination for heritage and spiritual tourism.",
    shortDescription: "Heritage State - History, Spirituality & Culture",
    heroImage: "https://images.unsplash.com/photo-1582407947304-fd86f028f716?w=1920&q=90",
    capital: "Lucknow",
    area: "243,286 km²",
    population: "200 million",
    languages: ["Hindi", "Urdu", "English"],
    bestTimeToVisit: "October to March",
    featured: true,
    isActive: true,
    order: 26,
    region: "North",
    metaTitle: "Uttar Pradesh Tourism - Heritage State Guide",
    metaDescription: "Experience Uttar Pradesh - Taj Mahal, Varanasi, Ayodhya, Lucknow. Heritage and spiritual tourism.",
    metaKeywords: "Uttar Pradesh, Taj Mahal, Varanasi, Ayodhya, Lucknow, heritage, spiritual tourism"
  },
  {
    name: "Uttarakhand",
    slug: "uttarakhand",
    description: "Uttarakhand, Dev Bhoomi (Land of Gods), is famous for its hill stations, spiritual significance, and adventure tourism. Known for Char Dham pilgrimage, hill stations like Mussoorie and Nainital, yoga capital Rishikesh, and beautiful valleys. A paradise for nature and spirituality lovers.",
    shortDescription: "Land of Gods - Hill Stations, Spirituality & Adventure",
    heroImage: "https://images.unsplash.com/photo-1585518419759-7fe2e0fbf8a6?w=1920&q=90",
    capital: "Dehradun",
    area: "53,483 km²",
    population: "10 million",
    languages: ["Hindi", "Garhwali", "Kumaoni", "English"],
    bestTimeToVisit: "April to June and September to November",
    featured: true,
    isActive: true,
    order: 27,
    region: "North",
    metaTitle: "Uttarakhand Tourism - Land of Gods Guide",
    metaDescription: "Explore Uttarakhand - Char Dham, hill stations, Rishikesh, Mussoorie, Nainital. Spiritual and nature tourism.",
    metaKeywords: "Uttarakhand, Char Dham, Rishikesh, Mussoorie, Nainital, hill stations, spiritual tourism"
  },
  {
    name: "West Bengal",
    slug: "west-bengal",
    description: "West Bengal is known for its rich culture, literature, delicious food, and diverse landscapes. Famous for Kolkata (City of Joy), Sundarbans mangrove forest, Darjeeling tea gardens, beautiful beaches, and intellectual heritage. A perfect blend of culture, nature, and tradition.",
    shortDescription: "Cultural Capital - Heritage, Nature & Culture",
    heroImage: "https://images.unsplash.com/photo-1582407947304-fd86f028f716?w=1920&q=90",
    capital: "Kolkata",
    area: "88,752 km²",
    population: "91 million",
    languages: ["Bengali", "Hindi", "English"],
    bestTimeToVisit: "October to March",
    featured: true,
    isActive: true,
    order: 28,
    region: "East",
    metaTitle: "West Bengal Tourism - Cultural Capital Guide",
    metaDescription: "Visit West Bengal - Kolkata, Sundarbans, Darjeeling, beaches, culture. Heritage and nature tourism.",
    metaKeywords: "West Bengal, Kolkata, Sundarbans, Darjeeling, culture, heritage, beaches"
  },
  // Union Territories
  {
    name: "Andaman and Nicobar Islands",
    slug: "andaman-nicobar",
    description: "Andaman and Nicobar Islands are India's tropical paradise with pristine beaches, crystal-clear waters, and rich marine life. Famous for Havelock Island, Radhanagar Beach, scuba diving, snorkeling, and untouched natural beauty. A perfect destination for beach lovers and adventure enthusiasts.",
    shortDescription: "Tropical Paradise - Beaches, Water Sports & Nature",
    heroImage: "https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?w=1920&q=90",
    capital: "Port Blair",
    area: "8,249 km²",
    population: "380,000",
    languages: ["Hindi", "English", "Bengali", "Tamil"],
    bestTimeToVisit: "October to May",
    featured: true,
    isActive: true,
    order: 29,
    region: "Other",
    metaTitle: "Andaman Nicobar Tourism - Tropical Paradise Guide",
    metaDescription: "Experience Andaman Nicobar - pristine beaches, scuba diving, Havelock Island, Port Blair. Beach and adventure tourism.",
    metaKeywords: "Andaman, Nicobar, Havelock Island, beaches, scuba diving, Port Blair, tropical paradise"
  },
  {
    name: "Delhi",
    slug: "delhi",
    description: "Delhi, the capital of India, is a perfect blend of history and modernity. Known for Red Fort, India Gate, Qutub Minar, Lotus Temple, bustling markets, delicious street food, and vibrant culture. A city that never sleeps with rich heritage and modern infrastructure.",
    shortDescription: "Capital City - Heritage, Culture & Modernity",
    heroImage: "https://images.unsplash.com/photo-1595658658481-d53d3f999875?w=1920&q=90",
    capital: "New Delhi",
    area: "1,484 km²",
    population: "19 million",
    languages: ["Hindi", "English", "Punjabi", "Urdu"],
    bestTimeToVisit: "October to March",
    featured: true,
    isActive: true,
    order: 30,
    region: "North",
    metaTitle: "Delhi Tourism - Capital City Guide",
    metaDescription: "Explore Delhi - Red Fort, India Gate, Qutub Minar, street food, culture. Heritage and modern tourism.",
    metaKeywords: "Delhi, New Delhi, Red Fort, India Gate, Qutub Minar, heritage, capital city"
  },
  {
    name: "Jammu and Kashmir",
    slug: "jammu-kashmir",
    description: "Jammu and Kashmir is known as Paradise on Earth for its stunning natural beauty. Famous for Srinagar, Dal Lake, houseboats, Gulmarg skiing, Pahalgam valleys, and breathtaking landscapes. A perfect destination for nature lovers, adventure enthusiasts, and honeymooners.",
    shortDescription: "Paradise on Earth - Nature, Adventure & Romance",
    heroImage: "https://images.unsplash.com/photo-1626621341517-bbf3d9990a23?w=1920&q=90",
    capital: "Srinagar (Summer), Jammu (Winter)",
    area: "42,241 km²",
    population: "12.5 million",
    languages: ["Kashmiri", "Urdu", "Hindi", "English"],
    bestTimeToVisit: "April to October (Summer) and December to February (Snow)",
    featured: true,
    isActive: true,
    order: 31,
    region: "North",
    metaTitle: "Jammu Kashmir Tourism - Paradise on Earth Guide",
    metaDescription: "Experience Jammu Kashmir - Srinagar, Dal Lake, Gulmarg, Pahalgam, houseboats. Nature and adventure paradise.",
    metaKeywords: "Jammu, Kashmir, Srinagar, Dal Lake, Gulmarg, Pahalgam, paradise, houseboats"
  },
  {
    name: "Ladakh",
    slug: "ladakh",
    description: "Ladakh, the Land of High Passes, is a high-altitude desert known for its stark beauty, Buddhist monasteries, and adventure tourism. Famous for Leh, Pangong Lake, Nubra Valley, adventure sports, and unique landscape. A destination for adventure seekers and spiritual travelers.",
    shortDescription: "Land of High Passes - Adventure, Spirituality & Nature",
    heroImage: "https://images.unsplash.com/photo-1626621341517-bbf3d9990a23?w=1920&q=90",
    capital: "Leh",
    area: "59,146 km²",
    population: "290,000",
    languages: ["Ladakhi", "Hindi", "English", "Urdu"],
    bestTimeToVisit: "May to September",
    featured: true,
    isActive: true,
    order: 32,
    region: "North",
    metaTitle: "Ladakh Tourism - Land of High Passes Guide",
    metaDescription: "Visit Ladakh - Leh, Pangong Lake, Nubra Valley, monasteries, adventure sports. High-altitude adventure destination.",
    metaKeywords: "Ladakh, Leh, Pangong Lake, Nubra Valley, monasteries, adventure, high altitude"
  },
  {
    name: "Puducherry",
    slug: "puducherry",
    description: "Puducherry (Pondicherry) is a charming French colony town known for its colonial architecture, serene beaches, Auroville, and unique blend of French and Indian cultures. Famous for French Quarter, Promenade Beach, Aurobindo Ashram, and peaceful atmosphere. A perfect destination for relaxation and spiritual seekers.",
    shortDescription: "French Riviera - Beaches, Heritage & Spirituality",
    heroImage: "https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?w=1920&q=90",
    capital: "Puducherry",
    area: "492 km²",
    population: "1.2 million",
    languages: ["Tamil", "French", "English", "Hindi"],
    bestTimeToVisit: "October to March",
    featured: false,
    isActive: true,
    order: 33,
    region: "South",
    metaTitle: "Puducherry Tourism - French Riviera Guide",
    metaDescription: "Explore Puducherry - French Quarter, beaches, Auroville, colonial architecture. Heritage and beach tourism.",
    metaKeywords: "Puducherry, Pondicherry, French Quarter, Auroville, beaches, colonial heritage"
  }
];

// Seed all states
const seedAllStates = async () => {
  try {
    console.log('🌱 Starting All India States Migration...\n');
    console.log(`📊 Total States/UTs to migrate: ${allStatesData.length}\n`);

    let created = 0;
    let updated = 0;

    for (const stateData of allStatesData) {
      try {
        // Check if state already exists
        const existingState = await State.findOne({ slug: stateData.slug });
        
        if (existingState) {
          await State.findOneAndUpdate({ slug: stateData.slug }, stateData, { new: true });
          updated++;
          console.log(`✅ Updated: ${stateData.name}`);
        } else {
          const state = new State(stateData);
          await state.save();
          created++;
          console.log(`✅ Created: ${stateData.name}`);
        }
      } catch (error) {
        console.error(`❌ Error processing ${stateData.name}:`, error.message);
      }
    }

    console.log(`\n🎉 Migration Complete!`);
    console.log(`📊 Summary:`);
    console.log(`   - States/UTs Created: ${created}`);
    console.log(`   - States/UTs Updated: ${updated}`);
    console.log(`   - Total Processed: ${created + updated} / ${allStatesData.length}`);

    process.exit(0);
  } catch (error) {
    console.error('❌ Migration error:', error);
    process.exit(1);
  }
};

// Run migration
seedAllStates();

